<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.gwt.personal.tupracticalpieces</groupId>
  <artifactId>TUPracticalPieces</artifactId>
  <version>6.0.0-SNAPSHOT</version>
  <packaging>war</packaging>
	<name>TUPracticalPieces Maven Webapp</name>
	<url>ec2-13-231-151-111.ap-northeast-1.compute.amazonaws.com'</url>
  
	<properties>
    	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    	<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<gwtVersion>2.12.1</gwtVersion>
        <gwtVersionSuffixGoogle></gwtVersionSuffixGoogle>
		<gwtVersionSuffixMojo></gwtVersionSuffixMojo>
		<gwt.extraJvmArgs>-Xmx1536m -Xss2560k</gwt.extraJvmArgs>
		<jettyVersion>12.0.16</jettyVersion>
		<jakartaVersion>ee10</jakartaVersion>
		<maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
        <maven.compiler.compilerId>javac</maven.compiler.compilerId>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
   		<maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
	</properties>

	<prerequisites>
		<maven>3.9.9</maven>
	</prerequisites>
	<repositories>
	  		<repository>
    			<id>central</id>
    			<url>https://repo1.maven.org/maven2/</url>
  			</repository>
 			<repository>
				<id>sonatype-google-releases</id>
				<name>Sonatype Google Releases</name>
				<url>https://oss.sonatype.org/service/local/repositories/google-releases/content</url>
			</repository>
		<!-- https://mvnrepository.com/artifact/com.google.gwt.google-apis/gwt-maps -->
			<repository>
				<id>opennms</id>
				<name>OPENNNMS</name>
				<url>https://repo.opennms.org/maven2/</url>
			</repository>		 
	</repositories>
   <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>libraries-bom</artifactId>
        <version>26.2.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

	<dependencies>
	
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
			<version>3.9.9</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-core</artifactId>
			<version>3.9.9</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-model</artifactId>
			<version>3.9.9</version>
			<scope>provided</scope>
		</dependency>

	<dependency>
    	<groupId>net.sourceforge.htmlunit</groupId>
    	<artifactId>htmlunit</artifactId>
    	<version>2.69.0</version> 
	
    	<exclusions>
        	<exclusion>
            	<groupId>xerces</groupId>
            	<artifactId>xercesImpl</artifactId>
        	</exclusion>
    	</exclusions>	
	
	 </dependency>

<!-- https://mvnrepository.com/artifact/org.gwtproject/gwt-servlet -->
		<dependency>
			<groupId>org.gwtproject</groupId>
			<artifactId>gwt-servlet-jakarta</artifactId>
			<version>${gwtVersion}${gwtVersionSuffixGoogle}</version>
			<scope>compile</scope>
		</dependency>

		
		<dependency>
 			<groupId>org.gwtproject</groupId>
			<artifactId>gwt-codeserver</artifactId>
			<version>${gwtVersion}${gwtVersionSuffixGoogle}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
 			<groupId>org.gwtproject</groupId>
			<artifactId>gwt-user</artifactId>
			<version>${gwtVersion}${gwtVersionSuffixGoogle}</version>
			<scope>provided</scope>
		</dependency>
		<!-- "provided" so that we don't deploy 
			<scope>provided</scope>
		-->
		<dependency>
 			<groupId>org.gwtproject</groupId>
			<artifactId>gwt-dev</artifactId>
			<version>${gwtVersion}${gwtVersionSuffixGoogle}</version>
			<scope>compile</scope>
			
										
										
						      <exclusions>
								<exclusion>
									<groupId>org.eclipse.jetty</groupId>
									<artifactId>apache-jsp</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.jetty</groupId>
									<artifactId>jetty-webapp</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.jetty</groupId>
									<artifactId>jetty-servlets</artifactId>
								</exclusion>
								<exclusion>
									<groupId>org.eclipse.jetty</groupId>
									<artifactId>jetty-annotations</artifactId>
								</exclusion>
								
								<exclusion>
									<groupId>org.eclipse.jetty.websocket</groupId>
									<artifactId>websocket-client</artifactId>
								</exclusion>
								
						      </exclusions> 
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.gwtproject.web.bindery/requestfactory-server -->
		<dependency>
			<groupId>org.gwtproject.web.bindery</groupId>
			<artifactId>requestfactory-server-jakarta</artifactId>
			<version>${gwtVersion}${gwtVersionSuffixGoogle}</version>
		</dependency>

		<dependency>
			<groupId>com.google.gwt.inject</groupId>
			<artifactId>gin</artifactId>
			<version>2.1.2</version>
			<scope>provided</scope>
		</dependency>
 


				<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-reload4j -->
				<dependency>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-reload4j</artifactId>
					<version>2.0.12</version>
				</dependency>
 				<dependency>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
					<version>2.0.12</version>
				</dependency>
	        

<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>3.1.0</version>
</dependency>

<!-- https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api -->

    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>6.0.0</version>
    </dependency>

	<!-- https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api -->
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<version>3.0.0</version>
		</dependency>
<!-- https://mvnrepository.com/artifact/jakarta.inject/jakarta.inject-api -->
		<dependency>
			<groupId>jakarta.inject</groupId>
			<artifactId>jakarta.inject-api</artifactId>
			<version>2.0.1</version>
		</dependency>

<!-- https://mvnrepository.com/artifact/jakarta.persistence/jakarta.persistence-api -->
<dependency>
    <groupId>jakarta.persistence</groupId>
    <artifactId>jakarta.persistence-api</artifactId>
    <version>3.1.0</version>
</dependency>
    

<!-- https://mvnrepository.com/artifact/org.eclipse.persistence/org.eclipse.persistence.jpa -->
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa</artifactId>
    <version>4.0.5</version>
</dependency>


<!-- https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink -->
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>eclipselink</artifactId>
    <version>4.0.5</version>
</dependency>

<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.core</artifactId>
    <version>4.0.5</version>
</dependency>


<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-util -->
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-util</artifactId>
    <version>12.0.16</version>
</dependency>

<!-- https://mvnrepository.com/artifact/org.eclipse.persistence/org.eclipse.persistence.json -->
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.json</artifactId>
    <version>4.0.5</version>
</dependency>

	<dependency>
		<groupId>mysql</groupId>
		<artifactId>mysql-connector-java</artifactId>
		<version>8.0.33</version>
	</dependency>



<!-- https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client-messagecrypto-bc -->
<dependency>
    <groupId>org.apache.pulsar</groupId>
    <artifactId>pulsar-client-messagecrypto-bc</artifactId>
    <version>3.3.0</version>
</dependency>




<dependency>
    <groupId>xerces</groupId>
    <artifactId>xercesImpl</artifactId>
    <version>2.11.0</version>
</dependency>

  		
  		<!-- https://mvnrepository.com/artifact/org.json/json -->
    	<dependency>
		    <groupId>org.json</groupId>
		    <artifactId>json</artifactId>
		    <version>20240303</version>
		</dependency>

  	
<!-- https://mvnrepository.com/artifact/org.json/json 
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20220924</version>
</dependency>
-->  		
  		
	<!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
	<dependency>
	    <groupId>commons-codec</groupId>
	    <artifactId>commons-codec</artifactId>
	    <version>1.10</version>
	</dependency>
		
<!-- https://mvnrepository.com/artifact/org.eclipse.jetty.ee10/jetty-ee10-servlet -->
  <dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-server</artifactId>
    <version>${jettyVersion}</version>
  </dependency>


<dependency>
    <groupId>org.eclipse.jetty.ee10</groupId>
    <artifactId>jetty-ee10-servlet</artifactId>
    <version>${jettyVersion}</version>
</dependency>

<!-- https://mvnrepository.com/artifact/org.eclipse.jetty.ee10/jetty-ee10-webapp -->
<dependency>
    <groupId>org.eclipse.jetty.ee10</groupId>
    <artifactId>jetty-ee10-webapp</artifactId>
    <version>${jettyVersion}</version>
</dependency>


<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-http -->
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-http</artifactId>
    <version>${jettyVersion}</version>
</dependency>

<!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-validator -->
<!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-validator -->
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>8.0.2.Final</version>
</dependency>

 </dependencies> 

<build>
		<!-- Generate compiled stuff in the folder used for development mode -->
		<outputDirectory>${project.build.directory}\${project.build.finalName}\WEB-INF\classes</outputDirectory>


<plugins>

<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-assembly-plugin -->

	<plugin>
		    <groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-assembly-plugin</artifactId>
		    <version>3.7.1</version>
		    <configuration>
			  <archive>
			    <manifest>
			      <mainClass>${main.class}</mainClass>
			    </manifest>
			  </archive>
			  <descriptorRefs>
			    <descriptorRef>jar-with-dependencies</descriptorRef>
			  </descriptorRefs>
		    </configuration>
		    <executions>
			<execution>
			    <id>make-assembly</id>
			    <phase>package</phase>
			    <goals>
				<goal>single</goal>
			    </goals>
			</execution>
		    </executions>
	</plugin>

        <!-- Add LIB folder to classPath -->

<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.4.2</version>
</plugin>


      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
        <configuration>
          <skip>true</skip>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      
      
<plugin>
<!-- We use this plugin to ensure that our usage of the
maven-jaxb2-plugin is JDK 8 compatible in absence of a fix
for https://java.net/jira/browse/MAVEN_JAXB2_PLUGIN-80. -->
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>properties-maven-plugin</artifactId>
    <!--
    <version>1.0-alpha-2</version> -->
    <version>1.0.0</version>
    <executions>
        <execution>
            <id>set-additional-system-properties</id>
            <goals>
                <goal>set-system-properties</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <properties>
            <property>
                <name>javax.xml.accessExternalSchema</name>
                <value>all</value>
            </property>
        </properties>
    </configuration>
	</plugin>

		<plugin>
		  <groupId>org.eclipse.jetty.ee10</groupId>
		  <artifactId>jetty-ee10-maven-plugin</artifactId>		  
		  <version>${jettyVersion}</version>
			<configuration>
			    <scan>0</scan>
<!--
			    <webApp>

					<contextPath>/TUPracticalPieces</contextPath>
					<descriptor>${project.build.directory}/${project.build.finalName}/WEB-INF/web.xml</descriptor>
 			        <defaultsDescriptor>${project.build.directory}/${project.build.finalName}/WEB-INF/webdefault-ee10.xml</defaultsDescriptor>
			    </webApp>
-->
			    <jettyXmls>/opt/jetty/etc/jetty.xml,/opt/jetty/etc/jetty-ssl-context.xml,/opt/jetty/etc/jetty-ssl.xml,/opt/jetty/etc/jetty-https.xml</jettyXmls>
 			    <webAppSourceDirectory>${project.build.directory}/${project.build.finalName}</webAppSourceDirectory>
			</configuration>
	        <dependencies>
 				<dependency>
					<groupId>org.eclipse.jetty.ee10</groupId>
				    	<artifactId>jetty-ee10-maven-plugin</artifactId>
				    	<version>12.0.2</version>				
					    <exclusions>
							<exclusion>
								<groupId>tomcat</groupId>
								<artifactId>tomcat-juli</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty</groupId>
								<artifactId>tomcat-juli</artifactId>
							</exclusion>
							<!--
							<exclusion>
								<groupId>org.gwtproject</groupId>
								<artifactId>gwt-dev</artifactId>
							</exclusion>
							-->	
							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>tomcat-juli</artifactId>
							</exclusion>

							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>websocket-common</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>websocket-servlet</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>websocket-api</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>websocket-server</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>javax-websocket-server-impl</artifactId>
							</exclusion>

							<exclusion>
								<groupId>javax.websocket</groupId>
								<artifactId>javax.websocket-api</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty.websocket</groupId>
								<artifactId>websocket-client</artifactId>
							</exclusion>

							<!--
							-->

							<exclusion>
								<groupId>org.eclipse.jetty</groupId>
								<artifactId>apache-jsp</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.mortbay.jasper</groupId>
								<artifactId>apache-jsp</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.mortbay.jasper</groupId>
								<artifactId>apache-el</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.eclipse.jetty</groupId>
								<artifactId>apache-jstl</artifactId>
							</exclusion>

							<exclusion>
								<groupId>org.eclipse.jetty.osgi</groupId>
								<artifactId>jetty-osgi-boot-jsp</artifactId>
							</exclusion>


					    </exclusions>

		        </dependency>	
	        </dependencies>
		</plugin>
     
	<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <verbose>ture</verbose>
          <fork>false</fork>
          <compilerVersion>$(maven.compiler.source)</compilerVersion>
 
          <annotationProcessors>
                     <annotationProcessor>com.google.web.bindery.requestfactory.apt.RfValidator</annotationProcessor>
          </annotationProcessors>
 			  	<source>17</source>
			  	<target>17</target>
				<release>17</release>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
         <excludes>
      		<!-- <exclude>com.google.gwt.personal.tupracticalpieces.client.content.auth.CwXFrame</exclude> -->
      		<!-- C:\tudev\wktupp2016r\TUPracticalPieces\src\main\java\com\google\gwt\personal\tupracticalpieces\client\content\auth\CwXFrame.java</exclude> -->
			<!-- <exclude>${basedir}\src\main\java\com\google\gwt\personal\tupracticalpieces\client\content\auth\CwXFrame.java</exclude> -->
	      </excludes>
	      <failOnError>false</failOnError>
        </configuration>
        <dependencies>

		<!-- https://mvnrepository.com/artifact/javax.validation/validation-api -->
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.0.Final</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/jakarta.platform/jakarta.jakartaee-api -->
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
			<version>10.0.0</version>
			<scope>compile</scope>
		</dependency>


	        
        </dependencies>

 	</plugin>
      
			<!-- GWT Maven Plugin -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>2.10.0</version>
					<configuration>
					<force>true</force>
                    <fork>false</fork>
							<!-- URL that should be automatically opened in the GWT shell (gwt:run). 
							<runTarget>TUPracticalPieces.html</runTarget>
							-->
							<runTarget>com.google.gwt.personal.tupracticalpieces/TUPracticalPieces.html</runTarget>
							<!-- Ask GWT to create the Story of Your Compile (SOYC) (gwt:compile) -->
							<compileReport>true</compileReport>
							<logLevel>ERROR</logLevel>
							<style>${gwt.style}</style>
 					        <!--  <sourceLevel>17</sourceLevel> 1.8-->
			    </configuration>
				<executions>
					<execution>
            			<id>gwtComplie</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
  		<artifactId>maven-war-plugin</artifactId>
  		<version>3.3.2</version> 
		<configuration>
    			<failOnMissingWebXml>false</failOnMissingWebXml> </configuration>
	</plugin>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-dependency-plugin</artifactId>
      <executions>
        <execution>
          <id>copy-dependencies</id>
          <phase>package</phase>
          <goals>
            <goal>copy-dependencies</goal>
          </goals>
          <configuration>
            <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/lib</outputDirectory>
          </configuration>
        </execution>
      </executions>
    </plugin>

			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.7</version>
				<executions>

					<execution>
						<id>copy-webabb</id>
						<phase>resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/${project.build.finalName}</outputDirectory>
							<resources>
								<resource>
									<directory>src/main/webapp</directory>
									
								</resource>
							</resources>
						</configuration>
					</execution>

					<execution>
						<id>copy-resorces</id>
						<phase>resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>
							<resources>
								<resource>
									<directory>src/main/resources</directory>
								</resource>
							</resources>
						</configuration>
					</execution>					
				</executions>
			</plugin>
</plugins>
	
	

<pluginManagement>
<plugins>
<plugin>
 <groupId>org.eclipse.m2e</groupId>
 <artifactId>lifecycle-mapping</artifactId>
 <version>1.0.0</version>
 <configuration>
   <lifecycleMappingMetadata>
     <pluginExecutions>

                <pluginExecution>
                  <pluginExecutionFilter>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>gwt-maven-plugin</artifactId>
					<version>${gwtVersion}${gwtVersionSuffixMojo}</version>
                    <goals>
                      <goal>debug</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore></ignore>
                  </action>
                </pluginExecution>
     </pluginExecutions>
   </lifecycleMappingMetadata>
 </configuration>
</plugin>
</plugins>
</pluginManagement>



</build>	
</project>

