# A default java.util.logging configuration.
# (All App Engine logging is through java.util.logging by default).
#
# To use this configuration, copy it into your application's WEB-INF
# folder and add the following to your appengine-web.xml:
# 
# <system-properties>
#   <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
# </system-properties>
#

# Set the default logging level for all loggers to WARNING
#.level = INFO


# Properties file which configures the operation of the JDK 
# logging facility.

# The system will look for this config file, first using 
# a System property specified at startup: 
# 
# >java -Djava.util.logging.config.file=myLoggingConfigFilePath 
# 
# If this property is not specified, then the config file is 
# retrieved from its default location at: 
# 
# JDK_HOME/jre/lib/logging.properties

# Global logging properties. 
# ------------------------------------------ 
# The set of handlers to be loaded upon startup. 
# Comma-separated list of class names. 
# (? LogManager docs say no comma here, but JDK example has comma.) 
#handlers=java.util.logging.FileHandler, java.util.logging.ConsoleHandler
handlers=java.util.logging.ConsoleHandler

# Default global logging level. 
# Loggers and Handlers may override this level 
#static Level	ALL 
#          The ALL has the lowest possible rank and is intended to turn on all logging.
#static Level	DEBUG 
#          The DEBUG Level designates fine-grained informational events that are most useful to debug an application.
#static Level	ERROR 
#          The ERROR level designates error events that might still allow the application to continue running.
#static Level	FATAL 
#          The FATAL level designates very severe error events that will presumably lead the application to abort.
#static Level	INFO 
#          The INFO level designates informational messages that highlight the progress of the application at coarse-grained level.
#static Level	OFF 
#          The OFF has the highest possible rank and is intended to turn off logging.
#static Level	TRACE 
#          The TRACE Level designates finer-grained informational events than the DEBUG
#static int	TRACE_INT 
#          TRACE level integer value.
#static Level	WARN 
#          The WARN level designates potentially harmful situations.
#.level=SEVERE
#.level=WARN
#.level=INFO
.level=DEBUG

# Handlers 
# -----------------------------------------

# --- ConsoleHandler --- 
# Override of global logging level 
#java.util.logging.ConsoleHandler.level=SEVERE 
java.util.logging.ConsoleHandler.level=DEBUG
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

# --- FileHandler --- 
# Override of global logging level 
#java.util.logging.FileHandler.level=ALL

# Naming style for the output file: 
# (The output file is placed in the directory 
# defined by the "user.home" System property.) 
#java.util.logging.FileHandler.pattern=%h/java%u.log

# Limiting size of output file in bytes: 
#java.util.logging.FileHandler.limit=50000

# Number of output files to cycle through, by appending an 
# integer to the base file name: 
#java.util.logging.FileHandler.count=1

# Style of output (Simple or XML): 
#java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
